spring:
  datasource:
    url: jdbc:mariadb://hanium-videomeeting.ccunwgycpela.ap-northeast-2.rds.amazonaws.com/videoMeeting
    username: hanium0098
    password: qwerty2!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql:
        format_sql: false # 배포 시 false로 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: hanium.videomeeting@gmail.com
    password: uwffkwpwhdkkpzxr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging.level:
  root: info
#  org.hibernate.SQL: debug
# 배포시 hibernate.SQL 주석처리

openvidu:
  url: https://15.165.67.176:443/
  secret: MY_SECRET

secret: hanium0098

cloud:
  aws:
    credentials:
      access-key: AKIAQKN3APRLPK3HW2OJ
      secret-key: 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
    s3:
      bucket: hanium-imagestorage
    region:
      static: ap-northeast-2
    stack:
      auto: false